name: dev-branches-names

on:
  push:
    branches: ["**"]
    branches-ignore:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          if [[ ! $BRANCH_NAME =~ ^feature/.* ]]; then
            echo "Development is only allowed in branches named feature/<feature_name>"
            exit 1
          fi
